### ISSUE TITLE
결과 페이지 수정

### ISSUE THREAD

**Issue by schio** [CDP-BETA/Developer-Interview-Question#3]
DEV-IQ에 맞춰 결과 페이지를 수정합니다.

- [x] Git 링크 수정
- [x] Discuss the quiz with others 버튼 삭제
- [x] 페이스북 공유 시 공유이미지 내 문구 PYTHON LEVEL CHALLENGE 문구를  DEV-IQ로 수정
- [x] 페이스북 공유 시 공유이미지 내 파이썬 로고 삭제

**Comment by zerone2** [comment]
파이썬 로고 -> 임의로 대체 
![image](https://user-images.githubusercontent.com/26848338/84107230-11c21f00-aa58-11ea-80dd-050d52996b69.png)
